version: '3'

tasks:
  build:
    cmds:
      - go build -v -race -o build/main main.go

  run:
    deps: [build]
    cmds:
      - ./build/main

  test:
    cmds:
      - gotest -race -cover ./...
    sources:
      - ./**/*.go

  lint:
    cmds:
      - golangci-lint run ./...
    sources:
      - ./**/*.go
      - .golangci.yaml

  format:
    cmds:
      - golangci-lint run --fix ./...
      - go mod tidy
    sources:
      - ./**/*.go
      - go.mod
      - go.sum
