name: ci

on:
  - push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - uses: actions/checkout@v3

      - name: Lint
        uses: golangci/golangci-lint-action@v3

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - uses: actions/checkout@v3

      - name: Build
        run: go build -v -race main.go

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - uses: actions/checkout@v3

      - name: Test
        run: |
          go install github.com/rakyll/gotest@latest
          gotest -race -cover ./...
